name: dbt_learn
version: 1.0.0
config-version: 2
profile: dbt_learn
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  dbt_learn:
    +materialized: view
# 👇 Add this block for seeds
seeds:
  dbt_learn:
    +quote_columns: false    # avoids quoting issues in Snowflake
    +column_types:           # optional: enforce Snowflake column types
      customer_id: integer
      first_name: varchar
      last_name: varchar
      email: varchar
      updated_at: varchar
      
      
      
      
      

